### ISSUE TITLE
url.add_or_replace_parameter(s) removes param values for param with multiple values

### ISSUE THREAD

**Issue by peonone** [scrapy/w3lib#137] opened 2019-09-18 03:22 UTC
url.add_or_replace_parameter(s) removes param values for param with multiple values, and only the last value is kept, even if the param name is not included in the param params.

```
url.add_or_replace_parameter('http://example.com/?foo=1&foo=2', 'bar', '3')                 
> http://example.com/?foo=2&bar=3
```

**Comment by Gallaecio** [comment] 2019-09-19 07:54
Duplicate of #125

**Closed by Gallaecio** 2019-09-19 07:54 UTC

**Comment by g-konst** [comment] 2020-01-29 12:50
@Gallaecio, when will the new version of `w3lib` with these fixes be available?
