### ISSUE TITLE
/w3lib/url.py

### ISSUE THREAD

**Issue by devNo0b** [scrapy/w3lib#51] opened 2016-04-07 05:09 UTC
Hi,

I'm not sure this is just me or we have this bug in this file /w3lib/url.py
unicode_to_str is not defined there. 
Is is used to be imported from there 
(from w3lib.util import unicode_to_str)
please advice

**Comment by redapple** [comment] 2016-04-07 08:02
@devNo0b ,
when does this bug appear for you? can you share a traceback perhaps?
What changed in your setup? did you upgrade w3lib yesterday to 1.14?

[`unicode_to_str` is defined](https://github.com/scrapy/w3lib/blob/331428f1e0365f55d49a7258d255979a866b414d/w3lib/util.py#L10) in current master branch and latest release 1.14
Changes in that area in 1.14 (see https://github.com/scrapy/w3lib/pull/45/files) were to use `to_bytes`, `to_unicode`, and `to_native_string` from `w3lib.utils` (like Scrapy did, deprecating `str_to_unicode` and `unicode_to_str`)
But these methods are still defined.

**Comment by Digenis** [comment] 2016-04-07 15:02
I guess devNo0b meant to say "I imported it from there"
like this: `from w3lib.url import unicode_to_str`.

@devNo0b, @kolyaflash (from #52),
this is not a bug.
It's just an engineering detail used for supporting both pythons.

Import it from w3lib.util if you want
but this is still not documented anywhere
and there's no guarantee it will remain there
as it's out of the scope of w3lib.

**Comment by kolyaflash** [comment] 2016-04-07 15:11
Hi @Digenis,
Thanks for explanation. 
I see. Well, we can't use urljoin_rfc (`scrapy.utils.url.urljoin_rfc`) then. I had close my PR.

**Comment by kolyaflash** [comment] 2016-04-07 15:24
@redapple 
> But these methods are still defined.

`unicode_to_str` is undefined in `url.py` (inside `urljoin_rfc`).

**Comment by redapple** [comment] 2016-04-07 15:30
@kolyaflash , ooh right! totally missed that.
`urljoin_rfc` has been deprecated for a long time (recommending to use `urlparse.urljoin`)
When I brought it back, I haven't checked the import...
Trouble with not having tests for it.

**Comment by devNo0b** [comment] 2016-04-08 02:00
For me i just switched back my docker image to use w3lib==1.13.0, but i guess latest version is fixed now.
Thanks @redapple, @kolyaflash @Digenis  for the fast responses and helps. Appreciate !

**Comment by redapple** [comment] 2016-04-11 15:19
Closed via https://github.com/scrapy/w3lib/issues/53

**Closed by redapple** 2016-04-11 15:19 UTC

**Comment by redapple** [comment] 2016-04-11 15:31
@devNo0b , [w3lib v1.14.2 is now on PyPI](https://pypi.python.org/pypi/w3lib/1.14.2).
Can I ask you to confirm if it fixes the issue for you?

**Comment by devNo0b** [comment] 2016-04-12 01:53
@redapple yup, thanks a lot for the fix
