### ISSUE TITLE
w3lib.http.headers_raw_to_dict doesn't give output I expect

### ISSUE THREAD

**Issue by iamminji** [scrapy/w3lib#81] opened 2016-12-20 11:42 UTC
My raw data is `"Content-type: text/html\n\rAccept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"`

I expect to see the output as
`"{'Content-type': ['text/html'], 'Accept': ['text/html', 'application/xhtml+xml', 'application/xml;q=0.9', 'image/webp', '*/*;q=0.8']}"`

but I got
`{'Content-type': ['text/html'], 'Accept': ['text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8']}`

I think [w3lib.http.headers_raw_to_dict](https://github.com/scrapy/w3lib/blob/master/w3lib/http.py) should be handled the comma.

thanks and best regards

**Comment by cathalgarvey** [comment] 2018-03-02 16:13
Hey @iamminji - Sorry this issue didn't receive a prompt response.

I think the intended behaviour of the function is to return one string per occurance of a header, because a header is not guaranteed to be unique in HTTP. So I think the current behaviour is "correct". However, a deeper parser that also parses the comma-and-semicolon-with-query-syntax-params information might be valuable also, as it's not only used for `Content-Type` but for things like encodings, language preferences, etc. also.

I'll close this issue as I don't think this is a bug or a problem to be resolved. But if you feel like contributing a deeper parser, by all means propose it. :)

**Closed by cathalgarvey** 2018-03-02 16:13 UTC
